name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
    create-folder:
        name: Create folder on Server
        runs-on: ubuntu-latest
        steps:
          - name: Creer un repertoire sur le server
            uses: appleboy/ssh-action@v1
            with:
              host: ${{ secrets.SERVER_HOST }}
              username: ${{ secrets.SERVER_USERNAME }}
              key: ${{ secrets.SERVER_SSH_PRIVATE_KEY}}
              port: ${{ secrets.SERVER_PORT }}
              script: |
                mkdir -p /opt/mes-naissances/newsite
